import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { NuqsAdapter } from 'nuqs/adapters/next';


const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NuqsAdapter>
        <TRPCReactProvider>
          <body
            className={`${inter.variable} antialiased`}
          >
            {children}
          </body>
        </TRPCReactProvider>
      </NuqsAdapter>
    </html>
  );
}
